controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#route Name
index:
    path: /hello
    controller: App\Controller\StudentController::helloAction
